name: animated_card_switcher
description: Animated card switcher
version: 1.0.0
author: obiwanzenobi
homepage: github.com/obiwanzenobi

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
